services:
  miplanta-backend-dev:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile.dev.backend
    ports:
      - "${DOCKER_PORT_BACK}:3000"
    depends_on:
      - miplanta-db-dev
    volumes:
      - ./BACKEND:/home/app/BACKEND
      - /home/app/BACKEND/node_modules
    env_file:
      - ./BACKEND/.env
    environment:
      - APP_HOST=0.0.0.0

  miplanta-frontend-dev:
    build:
      context: ./FRONTEND/MiPlantaFront
      dockerfile: Dockerfile.dev.frontend
    ports:
      - "${DOCKER_PORT_FRONT}:5173"
    volumes:
      - ./FRONTEND/MiPlantaFront:/home/app/FRONTEND
      - /home/app/FRONTEND/node_modules
    depends_on:
      - miplanta-backend-dev
    env_file:
      - ./FRONTEND/MiPlantaFront/.env

  miplanta-db-dev:
    image: mysql:8.0
    ports:
      - "${DB_PUERTO}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NOMBRE}
      MYSQL_ROOT_PASSWORD: ${DB_CONTRASENHA}
    volumes:
      - mysql-data-dev:/var/lib/mysql
      - ./BACKEND/initdb:/docker-entrypoint-initdb.d

volumes:
  mysql-data-dev:
