  services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile.dev.backend
      ports:
        - "${APP_PORT}:${APP_PORT}"
      depends_on:
        - miPlantaDB
      volumes:
        - .:/home/app/BACKEND
      env_file:
        - .env

    miPlantaDB:
      image: mysql
      ports:
        - "${DB_PUERTO}:3306"
      environment:
        MYSQL_DATABASE: ${DB_NOMBRE}
        MYSQL_ROOT_PASSWORD: ${DB_CONTRASENHA}
      volumes:
        - mysql-data:/var/lib/mysql
        - ./initdb:/docker-entrypoint-initdb.d

  volumes:
    mysql-data: